sudo: required
services:
  - docker

before_install:
  - docker build -t cab1729/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cab1729/react-test npm test -- --coverage

after_success:
  - docker build -t cab1729/multi-client ./client
  - docker build -t cab1729/multi-nginx ./nginx
  - docker build -t cab1729/multi-worker ./worker
  - docker build -t cab1729/multi-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push cab1729/multi-client
  - docker push cab1729/multi-nginx
  - docker push cab1729/multi-worker
  - docker push cab1729/multi-server
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket-name: elasticbeanstalk-us-east-1-987611515323
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY